`timescale 1ns/1ns
/* Generated by Yosys 0.7 (git sha1 61f6811, i686-w64-mingw32.static-gcc 4.9.3 -Os) */

(* top =  1  *)
(* src = "Q6.sv:2" *)
module Q6syn(a1, a0, b1, b0, c0, c2, s1, s0);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  (* src = "Q6.sv:2" *)
  input a0;
  (* src = "Q6.sv:2" *)
  input a1;
  (* src = "Q6.sv:2" *)
  input b0;
  (* src = "Q6.sv:2" *)
  input b1;
  (* src = "Q6.sv:2" *)
  input c0;
  (* src = "Q6.sv:2" *)
  output c2;
  (* src = "Q6.sv:2" *)
  output s0;
  (* src = "Q6.sv:2" *)
  output s1;
  NOT _17_ (
    .A(b1),
    .Y(_16_)
  );
  NOT _18_ (
    .A(a1),
    .Y(_00_)
  );
  NOR _19_ (
    .A(_00_),
    .B(_16_),
    .Y(_01_)
  );
  NOT _20_ (
    .A(b0),
    .Y(_02_)
  );
  NOT _21_ (
    .A(a0),
    .Y(_03_)
  );
  NOR _22_ (
    .A(_03_),
    .B(_02_),
    .Y(_04_)
  );
  NOT _23_ (
    .A(c0),
    .Y(_05_)
  );
  NOR _24_ (
    .A(a0),
    .B(b0),
    .Y(_06_)
  );
  NOR3 _25_ (
    .A(_06_),
    .B(_04_),
    .C(_05_),
    .Y(_07_)
  );
  NOR _26_ (
    .A(_07_),
    .B(_04_),
    .Y(_08_)
  );
  NOR _27_ (
    .A(a1),
    .B(b1),
    .Y(_09_)
  );
  NOR3 _28_ (
    .A(_09_),
    .B(_08_),
    .C(_01_),
    .Y(_10_)
  );
  NOR _29_ (
    .A(_10_),
    .B(_01_),
    .Y(_11_)
  );
  NOT _30_ (
    .A(_11_),
    .Y(c2)
  );
  NOR _31_ (
    .A(_06_),
    .B(_04_),
    .Y(_12_)
  );
  NOR _32_ (
    .A(_12_),
    .B(c0),
    .Y(_13_)
  );
  NOR _33_ (
    .A(_13_),
    .B(_07_),
    .Y(s0)
  );
  NOR _34_ (
    .A(_09_),
    .B(_01_),
    .Y(_14_)
  );
  NOR3 _35_ (
    .A(_14_),
    .B(_07_),
    .C(_04_),
    .Y(_15_)
  );
  NOR _36_ (
    .A(_15_),
    .B(_10_),
    .Y(s1)
  );
endmodule
